name: Prepare fortify-setup repository
runs:
  using: "composite"
  steps:
    - run: git clone https://$ACCESS_TOKEN:x-oauth-basic@github.com/PeculiarVentures/fortify-setup.git --depth=1 --branch=master
      shell: bash
    - run: yarn --cwd ./fortify-setup install --frozen-lockfile
      shell: bash
