FROM fedora:latest AS baseOS

RUN dnf install -y rpm-build @development-tools g++ nss-tools pcsc-lite pcsc-lite-ccid opensc pcsc-lite-devel
RUN curl -sL https://rpm.nodesource.com/setup_12.x | bash - && dnf -y install nodejs

RUN mkdir /fortify
COPY . /fortify

WORKDIR /fortify
RUN npm ci && npm install --save-dev electron-installer electron-installer-redhat
RUN npm run build

CMD [ "/bin/bash -c \"npx electron-installer-redhat --config /fortify/config/config.rpm.json \"" ]
