/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppFooter {
    }
    interface AppHeader {
    }
    interface AppRoot {
    }
    interface DocCode {
        "language": string;
    }
    interface DocPage {
        "path"?: string;
    }
    interface DocTab {
        "selected": boolean;
        "tab": string;
    }
    interface DocTabs {
    }
    interface LandingDevPage {
    }
    interface LandingUserPage {
    }
    interface NotfoundPage {
    }
}
declare global {
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDocCodeElement extends Components.DocCode, HTMLStencilElement {
    }
    var HTMLDocCodeElement: {
        prototype: HTMLDocCodeElement;
        new (): HTMLDocCodeElement;
    };
    interface HTMLDocPageElement extends Components.DocPage, HTMLStencilElement {
    }
    var HTMLDocPageElement: {
        prototype: HTMLDocPageElement;
        new (): HTMLDocPageElement;
    };
    interface HTMLDocTabElement extends Components.DocTab, HTMLStencilElement {
    }
    var HTMLDocTabElement: {
        prototype: HTMLDocTabElement;
        new (): HTMLDocTabElement;
    };
    interface HTMLDocTabsElement extends Components.DocTabs, HTMLStencilElement {
    }
    var HTMLDocTabsElement: {
        prototype: HTMLDocTabsElement;
        new (): HTMLDocTabsElement;
    };
    interface HTMLLandingDevPageElement extends Components.LandingDevPage, HTMLStencilElement {
    }
    var HTMLLandingDevPageElement: {
        prototype: HTMLLandingDevPageElement;
        new (): HTMLLandingDevPageElement;
    };
    interface HTMLLandingUserPageElement extends Components.LandingUserPage, HTMLStencilElement {
    }
    var HTMLLandingUserPageElement: {
        prototype: HTMLLandingUserPageElement;
        new (): HTMLLandingUserPageElement;
    };
    interface HTMLNotfoundPageElement extends Components.NotfoundPage, HTMLStencilElement {
    }
    var HTMLNotfoundPageElement: {
        prototype: HTMLNotfoundPageElement;
        new (): HTMLNotfoundPageElement;
    };
    interface HTMLElementTagNameMap {
        "app-footer": HTMLAppFooterElement;
        "app-header": HTMLAppHeaderElement;
        "app-root": HTMLAppRootElement;
        "doc-code": HTMLDocCodeElement;
        "doc-page": HTMLDocPageElement;
        "doc-tab": HTMLDocTabElement;
        "doc-tabs": HTMLDocTabsElement;
        "landing-dev-page": HTMLLandingDevPageElement;
        "landing-user-page": HTMLLandingUserPageElement;
        "notfound-page": HTMLNotfoundPageElement;
    }
}
declare namespace LocalJSX {
    interface AppFooter {
    }
    interface AppHeader {
    }
    interface AppRoot {
    }
    interface DocCode {
        "language"?: string;
    }
    interface DocPage {
        "path"?: string;
    }
    interface DocTab {
        "selected"?: boolean;
        "tab"?: string;
    }
    interface DocTabs {
    }
    interface LandingDevPage {
    }
    interface LandingUserPage {
    }
    interface NotfoundPage {
    }
    interface IntrinsicElements {
        "app-footer": AppFooter;
        "app-header": AppHeader;
        "app-root": AppRoot;
        "doc-code": DocCode;
        "doc-page": DocPage;
        "doc-tab": DocTab;
        "doc-tabs": DocTabs;
        "landing-dev-page": LandingDevPage;
        "landing-user-page": LandingUserPage;
        "notfound-page": NotfoundPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-footer": LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "doc-code": LocalJSX.DocCode & JSXBase.HTMLAttributes<HTMLDocCodeElement>;
            "doc-page": LocalJSX.DocPage & JSXBase.HTMLAttributes<HTMLDocPageElement>;
            "doc-tab": LocalJSX.DocTab & JSXBase.HTMLAttributes<HTMLDocTabElement>;
            "doc-tabs": LocalJSX.DocTabs & JSXBase.HTMLAttributes<HTMLDocTabsElement>;
            "landing-dev-page": LocalJSX.LandingDevPage & JSXBase.HTMLAttributes<HTMLLandingDevPageElement>;
            "landing-user-page": LocalJSX.LandingUserPage & JSXBase.HTMLAttributes<HTMLLandingUserPageElement>;
            "notfound-page": LocalJSX.NotfoundPage & JSXBase.HTMLAttributes<HTMLNotfoundPageElement>;
        }
    }
}
