/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppFooter {
    }
    interface AppHeader {
    }
    interface AppRoot {
    }
    interface DocCode {
        "language": string;
    }
    interface DocMenu {
    }
    interface DocNav {
        "items": IMenuItems;
    }
    interface DocPage {
        "path"?: string;
    }
    interface DocTab {
        "selected": boolean;
        "tab": string;
    }
    interface DocTabs {
    }
    interface LandingDevelopersPage {
    }
    interface LandingUsersPage {
    }
    interface NotfoundPage {
    }
}
declare global {
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDocCodeElement extends Components.DocCode, HTMLStencilElement {
    }
    var HTMLDocCodeElement: {
        prototype: HTMLDocCodeElement;
        new (): HTMLDocCodeElement;
    };
    interface HTMLDocMenuElement extends Components.DocMenu, HTMLStencilElement {
    }
    var HTMLDocMenuElement: {
        prototype: HTMLDocMenuElement;
        new (): HTMLDocMenuElement;
    };
    interface HTMLDocNavElement extends Components.DocNav, HTMLStencilElement {
    }
    var HTMLDocNavElement: {
        prototype: HTMLDocNavElement;
        new (): HTMLDocNavElement;
    };
    interface HTMLDocPageElement extends Components.DocPage, HTMLStencilElement {
    }
    var HTMLDocPageElement: {
        prototype: HTMLDocPageElement;
        new (): HTMLDocPageElement;
    };
    interface HTMLDocTabElement extends Components.DocTab, HTMLStencilElement {
    }
    var HTMLDocTabElement: {
        prototype: HTMLDocTabElement;
        new (): HTMLDocTabElement;
    };
    interface HTMLDocTabsElement extends Components.DocTabs, HTMLStencilElement {
    }
    var HTMLDocTabsElement: {
        prototype: HTMLDocTabsElement;
        new (): HTMLDocTabsElement;
    };
    interface HTMLLandingDevelopersPageElement extends Components.LandingDevelopersPage, HTMLStencilElement {
    }
    var HTMLLandingDevelopersPageElement: {
        prototype: HTMLLandingDevelopersPageElement;
        new (): HTMLLandingDevelopersPageElement;
    };
    interface HTMLLandingUsersPageElement extends Components.LandingUsersPage, HTMLStencilElement {
    }
    var HTMLLandingUsersPageElement: {
        prototype: HTMLLandingUsersPageElement;
        new (): HTMLLandingUsersPageElement;
    };
    interface HTMLNotfoundPageElement extends Components.NotfoundPage, HTMLStencilElement {
    }
    var HTMLNotfoundPageElement: {
        prototype: HTMLNotfoundPageElement;
        new (): HTMLNotfoundPageElement;
    };
    interface HTMLElementTagNameMap {
        "app-footer": HTMLAppFooterElement;
        "app-header": HTMLAppHeaderElement;
        "app-root": HTMLAppRootElement;
        "doc-code": HTMLDocCodeElement;
        "doc-menu": HTMLDocMenuElement;
        "doc-nav": HTMLDocNavElement;
        "doc-page": HTMLDocPageElement;
        "doc-tab": HTMLDocTabElement;
        "doc-tabs": HTMLDocTabsElement;
        "landing-developers-page": HTMLLandingDevelopersPageElement;
        "landing-users-page": HTMLLandingUsersPageElement;
        "notfound-page": HTMLNotfoundPageElement;
    }
}
declare namespace LocalJSX {
    interface AppFooter {
    }
    interface AppHeader {
    }
    interface AppRoot {
    }
    interface DocCode {
        "language"?: string;
    }
    interface DocMenu {
    }
    interface DocNav {
        "items"?: IMenuItems;
    }
    interface DocPage {
        "path"?: string;
    }
    interface DocTab {
        "selected"?: boolean;
        "tab"?: string;
    }
    interface DocTabs {
    }
    interface LandingDevelopersPage {
    }
    interface LandingUsersPage {
    }
    interface NotfoundPage {
    }
    interface IntrinsicElements {
        "app-footer": AppFooter;
        "app-header": AppHeader;
        "app-root": AppRoot;
        "doc-code": DocCode;
        "doc-menu": DocMenu;
        "doc-nav": DocNav;
        "doc-page": DocPage;
        "doc-tab": DocTab;
        "doc-tabs": DocTabs;
        "landing-developers-page": LandingDevelopersPage;
        "landing-users-page": LandingUsersPage;
        "notfound-page": NotfoundPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-footer": LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "doc-code": LocalJSX.DocCode & JSXBase.HTMLAttributes<HTMLDocCodeElement>;
            "doc-menu": LocalJSX.DocMenu & JSXBase.HTMLAttributes<HTMLDocMenuElement>;
            "doc-nav": LocalJSX.DocNav & JSXBase.HTMLAttributes<HTMLDocNavElement>;
            "doc-page": LocalJSX.DocPage & JSXBase.HTMLAttributes<HTMLDocPageElement>;
            "doc-tab": LocalJSX.DocTab & JSXBase.HTMLAttributes<HTMLDocTabElement>;
            "doc-tabs": LocalJSX.DocTabs & JSXBase.HTMLAttributes<HTMLDocTabsElement>;
            "landing-developers-page": LocalJSX.LandingDevelopersPage & JSXBase.HTMLAttributes<HTMLLandingDevelopersPageElement>;
            "landing-users-page": LocalJSX.LandingUsersPage & JSXBase.HTMLAttributes<HTMLLandingUsersPageElement>;
            "notfound-page": LocalJSX.NotfoundPage & JSXBase.HTMLAttributes<HTMLNotfoundPageElement>;
        }
    }
}
